version: '3.8'
services:
  app:
    build: .
    image: saif11bit/blogapp
    ports:
      - "80:80"
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - mydata:/mount/testvolumes


volumes:
  mydata:
    driver: azure_file
    driver_opts:
      share_name: testvolume
      storage_account_name: mysharestore