version: '3.8'
services:
  app:
    build: .
    ports:
      -"80:80"
    env_file: .env
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - ./data:/data/db